### ISSUE TITLE
Question about masscan usage

### ISSUE THREAD

**Issue by sirmodok** [sdcampbell/ScanCannon#1]
Is there a reason why you would use p.open and call the masscan binary directly rather than use something like python-masscan? Performance maybe? I was planning on developing something similar, but was trying to use the python-masscan  library. This looks more complicated, but more useful.

**Comment by sdcampbell** [comment]
It was simply a learning exercise at the time. I haven’t heard of Python-masscan. I’ll check it out. Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sirmodok** [comment]
I actually like your method better. I hope you don't mind if I use your code here as inspiration. I'm learning and attempting to create a tool while learning.
